trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:  
- stage: Build
  jobs:  
  - job: Build
    steps:
    - task: PowerShell@2
      displayName: Build
      inputs:
        filePath: './Cicd/build.ps1'
        workingDirectory: 'Cicd'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathtoPublish: '.build/'
        artifactName: '.build'
- stage: DeployDev
  dependsOn: Build
  jobs:
  - job: DeployDev
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '.build'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Azure'
        ScriptType: 'FilePath'
        ScriptPath: './Cicd/deploy.ps1'
        workingDirectory: 'Cicd'
        ScriptArguments: 'dev'
        azurePowerShellVersion: 'LatestVersion'
- stage: DeployProd
  dependsOn: Build
  jobs:
  - job: DeployProd
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '.build'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Azure'
        ScriptType: 'FilePath'
        ScriptPath: './Cicd/deploy.ps1'
        workingDirectory: 'Cicd'
        ScriptArguments: 'prod'
        azurePowerShellVersion: 'LatestVersion'
