trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:  
- stage: Build  
  jobs:  
  - job: BuildJob  
    steps:
    - task: PowerShell@2
      inputs:
        filePath: './Cicd/build.ps1'
        workingDirectory: 'Cicd'